// Docs: https://www.instantdb.com/docs/modeling-data

import { i } from "@instantdb/react";

const _schema = i.schema({
  entities: {
    $files: i.entity({
      path: i.string().unique().indexed(),
      url: i.string(),
    }),
    apiLoginCodes: i.entity({
      userId: i.string().indexed(),
      email: i.string().indexed(),
      codeHash: i.string(),
      expiresAt: i.number().indexed(),
      consumedAt: i.number().optional(),
      createdAt: i.number().indexed(),
    }),
    apiTokens: i.entity({
      userId: i.string().indexed(),
      tokenHash: i.string().indexed(),
      tokenPrefix: i.string().indexed(),
      expiresAt: i.number().indexed(),
      createdAt: i.number().indexed(),
    }),
    apiLoginAttempts: i.entity({
      action: i.string().indexed(),
      email: i.string().indexed(),
      ipHash: i.string().indexed(),
      outcome: i.string(),
      createdAt: i.number().indexed(),
    }),
    agentDeviceCodes: i.entity({
      deviceCodeHash: i.string().unique().indexed(),
      userCodeHash: i.string().unique().indexed(),
      userCodeDisplay: i.string().indexed(),
      agentName: i.string().indexed().optional(),
      status: i.string().indexed(),
      scope: i.string().indexed(),
      ownerId: i.string().indexed().optional(),
      expiresAt: i.number().indexed(),
      approvedAt: i.number().indexed().optional(),
      consumedAt: i.number().indexed().optional(),
      deniedAt: i.number().indexed().optional(),
      createdAt: i.number().indexed(),
      updatedAt: i.number().indexed(),
    }),
    apiUsers: i.entity({
      email: i.string().unique().indexed(),
      createdAt: i.number(),
      lastLoginCodeSentAt: i.number().optional(),
    }),
    skills: i.entity({
      ownerId: i.string().indexed(),
      name: i.string(),
      description: i.string().optional(),
      skillId: i.string().unique().indexed(),
      slug: i.string().indexed().optional(),
      status: i.string().indexed().optional(),
      visibility: i.string().indexed().optional(),
      sourceMode: i.string().indexed().optional(),
      originalRepoFullName: i.string().indexed().optional(),
      originalSkillPath: i.string().indexed().optional(),
      currentDraftVersionId: i.string().indexed().optional(),
      publishedVersionId: i.string().indexed().optional(),
      createdAt: i.number().indexed(),
      updatedAt: i.number().indexed().optional(),
      archivedAt: i.number().indexed().optional(),
    }),
    skillVersions: i.entity({
      ownerId: i.string().indexed(),
      skillId: i.string().indexed(),
      version: i.string().indexed(),
      status: i.string().indexed(),
      summary: i.string().optional(),
      manifestJson: i.json().optional(),
      createdAt: i.number().indexed(),
      updatedAt: i.number().indexed(),
      publishedAt: i.number().indexed().optional(),
    }),
    skillFiles: i.entity({
      ownerId: i.string().indexed(),
      skillId: i.string().indexed(),
      versionId: i.string().indexed(),
      fileKey: i.string().unique().indexed(),
      path: i.string().indexed(),
      kind: i.string().indexed(),
      mimeType: i.string().indexed().optional(),
      size: i.number().optional(),
      sha256: i.string().indexed().optional(),
      contentText: i.string().optional(),
      storageFileId: i.string().indexed().optional(),
      storageUrl: i.string().optional(),
      createdAt: i.number().indexed(),
      updatedAt: i.number().indexed(),
    }),
    publishingTargets: i.entity({
      ownerId: i.string().indexed(),
      skillId: i.string().indexed(),
      targetKind: i.string().indexed(),
      status: i.string().indexed(),
      repoFullName: i.string().indexed().optional(),
      installationId: i.string().indexed().optional(),
      skillRoot: i.string().indexed().optional(),
      baseBranch: i.string().indexed().optional(),
      autoMerge: i.boolean().optional(),
      consentStatus: i.string().indexed().optional(),
      configJson: i.json().optional(),
      createdAt: i.number().indexed(),
      updatedAt: i.number().indexed(),
    }),
    publishRuns: i.entity({
      ownerId: i.string().indexed(),
      skillId: i.string().indexed(),
      versionId: i.string().indexed(),
      targetKind: i.string().indexed(),
      status: i.string().indexed(),
      startedAt: i.number().indexed(),
      completedAt: i.number().indexed().optional(),
      pullRequestUrl: i.string().optional(),
      error: i.string().optional(),
      detailsJson: i.json().optional(),
    }),
    directorySubmissions: i.entity({
      ownerId: i.string().indexed(),
      skillId: i.string().indexed(),
      versionId: i.string().indexed(),
      targetKind: i.string().indexed(),
      status: i.string().indexed(),
      packetJson: i.json().optional(),
      externalUrl: i.string().optional(),
      createdAt: i.number().indexed(),
      updatedAt: i.number().indexed(),
    }),
    skillUsageEvents: i.entity({
      ownerId: i.string().indexed(),
      skillId: i.string().indexed(),
      eventKind: i.string().indexed(),
      versionId: i.string().indexed().optional(),
      path: i.string().indexed().optional(),
      source: i.string().indexed().optional(),
      subjectHash: i.string().indexed().optional(),
      dayKey: i.string().indexed(),
      metadataJson: i.json().optional(),
      createdAt: i.number().indexed(),
    }),
    githubInstallations: i.entity({
      ownerId: i.string().indexed().optional(),
      installationId: i.string().unique().indexed(),
      accountLogin: i.string().indexed(),
      accountType: i.string().indexed(),
      repositorySelection: i.string().indexed().optional(),
      permissionsJson: i.json().optional(),
      createdAt: i.number().indexed(),
      updatedAt: i.number().indexed(),
    }),
    githubRepositories: i.entity({
      ownerId: i.string().indexed().optional(),
      installationId: i.string().indexed(),
      repositoryId: i.string().unique().indexed(),
      repoFullName: i.string().indexed(),
      defaultBranch: i.string().indexed().optional(),
      selected: i.boolean().optional(),
      createdAt: i.number().indexed(),
      updatedAt: i.number().indexed(),
    }),
    skillImports: i.entity({
      ownerId: i.string().indexed(),
      repoFullName: i.string().indexed(),
      status: i.string().indexed(),
      discoveredCount: i.number().optional(),
      importedCount: i.number().optional(),
      consentStatus: i.string().indexed().optional(),
      createdAt: i.number().indexed(),
      updatedAt: i.number().indexed(),
    }),
    feedback: i.entity({
      ownerId: i.string().indexed(),
      skillId: i.string().indexed(),
      rating: i.string().indexed(),
      feedback: i.string(),
      ipHash: i.string().optional(),
      createdAt: i.number().indexed(),
    }),
  },
  links: {
    skillFileStorageFile: {
      forward: {
        on: "skillFiles",
        has: "one",
        label: "storageFile",
      },
      reverse: {
        on: "$files",
        has: "many",
        label: "skillFiles",
      },
    },
  },
});

// This helps TypeScript display nicer intellisense
type _AppSchema = typeof _schema;
interface AppSchema extends _AppSchema {}
const schema: AppSchema = _schema;

export type { AppSchema };
export default schema;
